### ISSUE TITLE
MDHLDB.lua error

### ISSUE THREAD

**Issue by Psychosi42** [The-Sickness/MisDirectionHelper#4]
7x MisDirectionHelper2/MDHLDB.lua:39: attempt to call field 'GetSpellInfo' (a nil value)
[string "@MisDirectionHelper2/MDHLDB.lua"]:39: in main chunk

Locals:
LibStub = <table> {
 NewLibrary = <function> defined @LibDBIcon-1.0/LibStub/LibStub.lua:20
 minors = <table> {
 }
 minor = 2
 IterateLibraries = <function> defined @LibDBIcon-1.0/LibStub/LibStub.lua:46
 GetLibrary = <function> defined @LibDBIcon-1.0/LibStub/LibStub.lua:36
 libs = <table> {
 }
}
AceDB = <table> {
 db_registry = <table> {
 }
 frame = Frame {
 }
 New = <function> defined @Alts/Libs/AceDB-3.0/AceDB-3.0.lua:705
}
AceAddon = <table> {
 DisableAddon = <function> defined @Alts/Libs/AceAddon-3.0/AceAddon-3.0.lua:551
 EnableAddon = <function> defined @Alts/Libs/AceAddon-3.0/AceAddon-3.0.lua:516
 EmbedLibrary = <function> defined @Alts/Libs/AceAddon-3.0/AceAddon-3.0.lua:182
 InitializeAddon = <function> defined @Alts/Libs/AceAddon-3.0/AceAddon-3.0.lua:493
 IterateAddonStatus = <function> defined @Alts/Libs/AceAddon-3.0/AceAddon-3.0.lua:593
 EmbedLibraries = <function> defined @Alts/Libs/AceAddon-3.0/AceAddon-3.0.lua:164
 initializequeue = <table> {
 }
 statuses = <table> {
 }
 GetAddon = <function> defined @Alts/Libs/AceAddon-3.0/AceAddon-3.0.lua:149
 NewAddon = <function> defined @Alts/Libs/AceAddon-3.0/AceAddon-3.0.lua:101
 IterateModulesOfAddon = <function> defined @Alts/Libs/AceAddon-3.0/AceAddon-3.0.lua:598
 IterateEmbedsOnAddon = <function> defined @Alts/Libs/AceAddon-3.0/AceAddon-3.0.lua:597
 embeds = <table> {
 }
 IterateAddons = <function> defined @Alts/Libs/AceAddon-3.0/AceAddon-3.0.lua:583
 frame = AceAddon30Frame {
 }
 addons = <table> {
 }
 enablequeue = <table> {
 }
}
AceConfig = <table> {
 RegisterOptionsTable = <function> defined @Alts/Libs/AceConfig-3.0/AceConfig-3.0.lua:45
}
AceConfigDialog = <table> {
 ConfigTableChanged = <function> defined @Alts/Libs/AceConfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:1816
 CloseAll = <function> defined @Alts/Libs/AceConfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:1797
 Close = <function> defined @Alts/Libs/AceConfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:1807
 SetDefaultSize = <function> defined @Alts/Libs/AceConfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:1827
 tooltip = AceConfigDialogTooltip {
 }
 Open = <function> defined @Alts/Libs/AceConfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:1842
 AddToBlizOptions = <function> defined @Alts/Libs/AceConfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:1974
 BlizOptions = <table> {
 }
 popup = Frame {
 }
 GetStatusTable = <function> defined @Alts/Libs/AceConfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:401
 OpenFrames = <table> {
 }
 Status = <table> {
 }
 frame = Frame {
 }
 FeedGroup = <function> defined @Alts/Libs/AceConfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:1587
 SelectGroup = <function> defined @Alts/Libs/AceConfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:431
}
icon = <table> {
 Register = <function> defined @LibDBIcon-1.0/LibDBIcon-1.0/LibDBIcon-1.0.lua:372
 callbacks = <table> {
 }
 Unlock = <function> defined @LibDBIcon-1.0/LibDBIcon-1.0/LibDBIcon-1.0.lua:389
 IsButtonInCompartment = <function> defined @LibDBIcon-1.0/LibDBIcon-1.0/LibDBIcon-1.0.lua:491
 IsButtonCompartmentAvailable = <function> defined @LibDBIcon-1.0/LibDBIcon-1.0/LibDBIcon-1.0.lua:485
 Lock = <function> defined @LibDBIcon-1.0/LibDBIcon-1.0/LibDBIcon-1.0.lua:378
 ShowOnEnter = <function> defined @LibDBIcon-1.0/LibDBIcon-1.0/LibDBIcon-1.0.lua:441
 SetButtonToPosition = <function> defined @LibDBIcon-1.0/LibDBIcon-1.0/LibDBIcon-1.0.lua:477
 SetButtonRadius = <function> defined @LibDBIcon-1.0/LibDBIcon-1.0/LibDBIcon-1.0.lua:468
 Unr

**Comment by The-Sickness** [comment]
I made a mistake, that update was just for 11.0. It will not work in 10.2.7. Just roll back one and you will be fine.

**Comment by The-Sickness** [comment]
10.2.7 users just roll back one and you will be fine. The last update was for 11.0 only. I made a mistake when uploading.
